OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Запазено",
    "Error" : "Грешка",
    "Breeze Dark" : "Breeze Dark тема",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : " Breeze Dark Тема за Nextcloud, базирана на темата на KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Breeze Dark\nТова е тъмна бриз тема за Nextcloud, базирана на темата Breeze Dark, направена по проекта KDE.\n\n## Използване\n\nСлед като инсталирате темата, трябва да я активирате. Има две опции за това, глобална и лична.\n\n### Глобална\n\nГлобалната опция активира по подразбиране темата за всички потребители и за посещения без удостоверяване. Без тази опция елементи като страницата за вход и тази за споделяне, няма да бъдат оформени. Има и опция да изключите темата на страницата за вход. Можете да намерите глобалните опции тук:\n\n```\nНастройки на администратора > Теми > Breeze Dark\n```\n\nМоля, имайте предвид, че е необходимо приложението Theming/Теми/ да е активирано в Nextcloud, за да получите достъп до глобалните настройки.\n\n###Лични\n\nЛичната опция позволява на всеки потребител да зададе свои собствени предпочитания, независимо от това как сте задали глобалната опция. Ако потребителят все още не е задал опция, той ще следва глобалната опция. Можете да намерите личната опция тук:\n\n```\nЛични настройки > Достъпност > Breeze Dark\n```\n\nМоля, имайте предвид, чее необходимо приложението Accessibility/Достъпност/, да е активирано в Nextcloud, за да получите достъп до личната настройка.\n\n### Персонализирано оформление\n\nВ раздел Theming, в настройките на администратора можете да добавите ваше собствено персонализирано оформление към темата. Може да се използва само стандартен CSS. Този персонализиран стил ще се прилага винаги, когато темата е активирана и засяга само темата Breeze Dark.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Тъмна тема, базирана на Breeze Dark към проект KDE. Моля, опреснете страницата, за да влязат в сила промените.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Тази настройка ще активира темата по подразбиране за всички неудостоверени потребители и потребители, които не са задали предпочитание.",
    "Enable Breeze Dark theme by default" : "Активиране на Breeze Dark тема по подразбиране",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Тази настройка ще ви позволи да изберете дали да приложите темата на страницата за вход, когато темата е активирана по подразбиране.",
    "Theme the login page" : "Прилагане на тема на страницата за вход",
    "Custom Styling" : "Персонализирано Оформление",
    "Insert custom styling here …" : " Вмъкнете персонализирано оформление тук ...",
    "Save" : "Запиши",
    "A Breeze Dark theme for Nextcloud." : "Breeze Dark Тема за Nextcloud",
    "Breeze Dark theme" : "Breeze Dark тема",
    "Enable Breeze Dark theme" : "Активиране на Breeze Dark тема"
},
"nplurals=2; plural=(n != 1);");
