OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Uloženo",
    "Error" : "Chyba",
    "Breeze Dark" : "Breeze Dark",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Motiv vzhledu Breeze Dark pro Nextcloud, založený na motivu od KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Breeze Dark\nJe tmavý motiv vzhledu pro Nextcloud, založený na stejnojmenném z projektu KDE.\n\n## Použití\n\nPo nainstalování motivu vzhledu je třeba ho zapnout. To je možné buď pro všechny, nebo jednotlivými uživateli.\n\n### Pro všechny\n\nGlobální předvolba zapne motiv ve výchozím stavu pro všechny uživatele a nepřihlášené návštěvníky. Bez této předvolby nebudou věci jako přihlašovací stránky a ty pro sdílení opatřeny tímto motivem. Je zde také možnost neopatřovat přihlašovací stránku motivem vzhledu. Globální předvolby naleznete tady:\n\n```\nNastavení správy > Motiv vzhledu > Breeze Dark\n```\n\nPoznamenejme, že aby byla globální nastavení přístupná, je třeba mít zapnutou aplikaci Opatřování motivem vzhledu.\n\n### Jednotlivými uživateli\n\nOsobní nastavení umožňuje každému z uživatelů si nastavit své vlastní předvolby nezávisle na globálních nastaveních. Pokud uživatel doposud nenastavil, bude následovat globální nastavení. Osobní nastavení naleznete tady:\n\n```\nOsobní nastavení > Zpřístupnění > Breeze Dark\n```\n\nPoznamenejme, že aby byla tato nastavení přístupná, je třeba mít zapnutou aplikaci Zpřístupnění.\n\n### Uživatelsky určené opatřování motivem vzhledu\n\nV sekci Opatřování motivem vzhledu v nastavení správy je možné přidat motivu uživatelsky určené styly. Je možné použít pouze standardní CSS styly. Tyto uživatelsky určené styly budou uplatněny kdekoli je motiv zapnutý a týká se pouze motivu vzhledu Breeze Dark.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Tmavý motiv vzhledu založený na Breeze Dark z projektu KDE. Aby se změny projevily, načtěte stránku znovu.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Toto nastavení zapne motiv jako výchozí pro všechny nepřihlášené uživatele a ty, kteří si nenastavili svou předvolbu.",
    "Enable Breeze Dark theme by default" : "Nastavit jako výchozí tmavý motiv vzhledu",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Toto nastavení umožňuje zvolit zda má být přihlašovací stránka opatřena motivem vzhledu v případě, že je tento zapnutý jako výchozí.",
    "Theme the login page" : "Opatřit přihlašovací stránku motivem vzhledu",
    "Custom Styling" : "Uživatelsky určené opatření styly",
    "Insert custom styling here …" : "Sem vložte své vlastní styly…",
    "Save" : "Uložit",
    "A Breeze Dark theme for Nextcloud." : "Motiv vzhledu Breeze Dark pro Nextcloud.",
    "Breeze Dark theme" : "Motiv vzhledu Breeze Dark",
    "Enable Breeze Dark theme" : "Zapnout motiv vzhledu Breeze Dark"
},
"nplurals=4; plural=(n == 1 && n % 1 == 0) ? 0 : (n >= 2 && n <= 4 && n % 1 == 0) ? 1: (n % 1 != 0 ) ? 2 : 3;");
