OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Αποθηκεύτηκε",
    "Error" : "Σφάλμα",
    "Breeze Dark" : "Σκούρο Breeze",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Θέμα Σκούρο Breeze για το Nextcloud, βασισμένο στο θέμα του KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Σκούρο Breeze\nΑυτό είναι ένα το θέμα σκούρο breeze για το Nextcloud, βασισμένο στο θέμα Σκούρο Breeze που δημιουργήθηκε από το Έργο KDE.\n\n## Χρήση\n\nΑφού εγκαταστήσετε το θέμα, πρέπει να το ενεργοποιήσετε. Υπάρχουν δύο επιλογές για αυτό, μια καθολική και μια προσωπική.\n\n### Καθολική\n\nΗ καθολική επιλογή ενεργοποιεί το θέμα από προεπιλογή για όλους τους χρήστες και μη πιστοποιημένους επισκέπτες. Χωρίς αυτήν την επιλογή, τα στοιχεία όπως οι σελίδες σύνδεσης και κοινής χρήσης δεν θα έχουν στυλ. Υπάρχει επίσης μια επιλογή για να εξαιρέσετε τη σελίδα σύνδεσης από την εφαρμογή θέματος. Μπορείτε να βρείτε τις καθολικές επιλογές εδώ:\n\n```\nΡυθμίσεις διαχειριστή> Θέμα> Σκούρο Breeze\n```\n\nΛάβετε υπόψη ότι χρειάζεστε την εφαρμογή Θέματα ενεργοποιημένη στο Nextcloud για πρόσβαση στις καθολικές ρυθμίσεις.\n\n### Προσωπική\n\nΗ προσωπική επιλογή επιτρέπει σε κάθε χρήστη να ορίσει τη δική του προτίμηση ανεξάρτητα από τον τρόπο που ορίζετε την καθολική επιλογή. Εάν ο χρήστης δεν έχει ορίσει μια επιλογή, θα ακολουθήσει την καθολική επιλογή. Μπορείτε να βρείτε την προσωπική επιλογή εδώ:\n\n```\nΠροσωπικές ρυθμίσεις> Προσβασιμότητα> Σκούρο Breeze\n```\n\nΛάβετε υπόψη ότι χρειάζεστε την εφαρμογή Προσβασιμότητα ενεργοποιημένη στο Nextcloud για να αποκτήσετε πρόσβαση στην προσωπική ρύθμιση.\n\n### Προσαρμοσμένο στυλ\n\nΣτην ενότητα Θέμα στις ρυθμίσεις διαχειριστή, μπορείτε να προσθέσετε το δικό σας προσαρμοσμένο στυλ στο θέμα. Μόνο το τυπικό CSS μπορεί να χρησιμοποιηθεί. Αυτό το προσαρμοσμένο στυλ θα εφαρμόζεται όποτε είναι ενεργοποιημένο το θέμα και επηρεάζει μόνο το θέμα Σκούρο Breeze.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Ένα σκοτεινό θέμα βασισμένο στο Σκούρο Breeze από το έργο KDE. Παρακαλούμε ανανεώστε τη σελίδα για να ισχύσουν οι αλλαγές.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Αυτή η ρύθμιση θα ενεργοποιήσει το θέμα από προεπιλογή, για τυχόν μη πιστοποιημένους χρήστες και χρήστες που δεν έχουν ορίσει μια προτίμηση.",
    "Enable Breeze Dark theme by default" : "Ενεργοποίηση από προεπιλογή του θέματος Σκούρο Breeze",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Αυτή η ρύθμιση θα σας επιτρέψει να επιλέξετε εάν η σελίδα σύνδεσης πρέπει να έχει θέμα όταν το θέμα είναι ενεργοποιημένο από προεπιλογή.",
    "Theme the login page" : "Θέμα για την σελίδα σύνδεσης",
    "Custom Styling" : "Προσαρμοσμένο στυλ",
    "Insert custom styling here …" : "Εισαγάγετε προσαρμοσμένο στυλ εδώ …",
    "Save" : "Αποθήκευση",
    "A Breeze Dark theme for Nextcloud." : "Ένα σκούρο θέμα Breeze για το Nextcloud.",
    "Breeze Dark theme" : "Σκούρο θέμα Breeze",
    "Enable Breeze Dark theme" : "Ενεργοποίηση θέματος Σκούρο Breeze"
},
"nplurals=2; plural=(n != 1);");
