OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Guardado",
    "Error" : "Error",
    "Breeze Dark" : "Breeze Dark",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Tema Breeze Dark para Nextcloud, basado en el tema de KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Breeze Dark\nEste es un tema oscuro de Breeze para Nextcloud, basado en el tema Breeze Dark hecho por el Proyecto KDE.\n\n## Uso\n\nDespués de instalar el tema, necesitas habilitarlo. Hay dos opciones para esto, una global y otra personal.\n\n### Global\n\nLa opción global habilita el tema por defecto para todos los usuarios y visitas no autenticadas. Sin esta opción, elementos como las páginas de inicio de sesión y para compartir no tendrán estilo. También hay una opción para excluir la página de inicio de sesión de ser tematizada. Puedes encontrar las opciones globales aquí:\n\n```\nAjustes > Temas > Breeze Dark\n```\n\nPor favor, ten en cuenta que necesitas la aplicación Temas habilitada en Nextcloud para acceder a las opciones globales.\n\n### Personal\n\nLa opción personal permite a cada usuario establecer sus propias preferencias independientemente de cómo se haya establecido la opción global. Si el usuario no ha establecido una opción todavía, seguirá la opción global. Puedes encontrar la opción personal aquí:\n\n```\nAjustes > Accesibilidad > Breeze Dark\n```\n\nPor favor, ten en cuenta que necesitas la aplicación de Accesibilidad activada en Nextcloud para acceder a la configuración personal.\n\n### Estilo personalizado\n\nEn la sección de Temas de los Ajustes puedes añadir tu propio estilo personalizado al tema. Sólo se puede utilizar el CSS estándar. Este estilo personalizado se aplicará siempre que el tema esté habilitado y sólo afecta al tema Breeze Dark.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Un tema oscuro basado en Breeze Dark hecho por el Proyecto KDE. Por favor, refresca la página para que los cambios tengan efecto.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Este ajuste activa el tema por defecto, para cualquier usuario no autenticado y usuarios que no hayan establecido una preferencia.",
    "Enable Breeze Dark theme by default" : "Activa el tema Breeze Dark por defecto",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Este ajuste te permitirá elegir si la página de inicio de sesión debe ser tematizada cuando el tema esté activado por defecto.",
    "Theme the login page" : "Tematizar la página de inicio de sesión",
    "Custom Styling" : "Estilo personalizado",
    "Insert custom styling here …" : "Define el estilo personalizado aquí …",
    "Save" : "Guardar",
    "A Breeze Dark theme for Nextcloud." : "El tema Breeze Dark para Nextcloud.",
    "Breeze Dark theme" : "Tema Breeze Dark ",
    "Enable Breeze Dark theme" : "Activar tema Breeze Dark"
},
"nplurals=2; plural=(n != 1);");
