OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Gordeta",
    "Error" : "Errorea",
    "Breeze Dark" : "Breeze Dark",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Breeze Dark gaia Nextcloud-erako, KDE-ren gaian oinarrituta",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "#Breeze Dark\nHau Nextcloud-eko breeze dark da, KDE proiektuak egindako Breeze Dark gaian oinarrituta\n\n## Erabilera\n\nGaia instalatu ondoren, gaitu egin behar duzu. Horretarako 2 aukera daude, orokorra eta pertsonala.\n\n### Orokorra\n\nAukera orokorrak gaia gaitzen du lehenespenez erabiltzaile guztientzat eta autentifikatu gabeko bisitetarako. Aukera hau gabe saioa hasteko eta partekatzeko orriak bezalako gauzak ez dira estilizatuko. Saio hasiera orrialdea gaitik kanpo uzteko aukera ere badago, gainerakoak barne diren bitartean. Hemen aurkituko dituzu aukera orokorrak:\n```\n\nAdministratzaile ezarpenak> Gaia> Breeze Dark\n```\n\nKontuan izan Nextcloud-en ezarpen pertsonalera sartzeko Gaiak-aplikazioa gaituta behar duzula.\n\n### Pertsonala\n\nAukera pertsonalari esker, erabiltzaile bakoitzak bere lehentasunak ezar ditzake, aukera orokorra ezartzeko moduaz independienteki. Erabiltzaileak aukerarik ezarri ezean, aukera orokorrek jarraituko dute. Aukera pertsonala hemen aurkitu dezakezu:\n\n```\nEzarpen pertsonalak> Irisgarritasuna> Breeze dark\n```\n\n## Estilo pertsonalizatua\n\nAdministrazio-ezarpenetako Gaiak atalean zure estilo pertsonalizatua gehitu diezaiokezu gaiari. CSS estandarra soilik erabil daiteke. Estilo pertsonalizatu hau gaia gaituta dagoenean eta Breeze Dark gaiari soilik eragiten dionean aplikatuko da.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "KDE proiektuaren Breeze Dark-en oinarritutako gai iluna. Freskatu orria aldaketak indarrean jartzeko.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Ezarpen honek gaia lehenespenez gaituko du autentifikatu gabeko erabiltzaileentzat eta hobespenik ezarri ez duten erabiltzaileentzat.",
    "Enable Breeze Dark theme by default" : "Gaitu Breeze Dark gaia lehenespenez",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Ezarpen honi esker aukeratu ahal izango da saio-hasierako orrialdeak gaia ezarrita behar duen, gaia lehenespenez gaituta dagoenean.",
    "Theme the login page" : "Saio-hasierari gaia ezarri",
    "Custom Styling" : "Estilo pertsonalizatua",
    "Insert custom styling here …" : "Txertatu estilo pertsonalizatua hemen ...",
    "Save" : "Gorde",
    "A Breeze Dark theme for Nextcloud." : "Breeze Dark gaia Nextclouderako.",
    "Breeze Dark theme" : "Breeze Dark gaia",
    "Enable Breeze Dark theme" : "Gaitu Breeze Dark gaia"
},
"nplurals=2; plural=(n != 1);");
