OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Сохранено",
    "Error" : "Ошибка",
    "Breeze Dark" : "Breeze Dark",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Тема Breeze Dark для Nextcloud, основанная на теме KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Breeze Dark\nЭто лёгкая тёмная тема для Nextcloud, основанная на теме Breeze Dark, созданной проектом KDE.\n\n## Использование\n\nПосле установки темы её необходимо включить. Для этого есть два варианта: глобальный и персональный.\n\n### Глобальный\n\nГлобальный параметр включает тему по умолчанию для всех пользователей и пользователей не прошедших проверку подлинности. Без этой опции элементы, такие как страницы входа и обмена, не будут стилизованы. Также есть возможность исключить тематическую страницу входа. Здесь вы можете найти глобальные параметры:\n\n``\nНастройки администратора > Темы > Breeze Dark\n``\n\nОбратите внимание, что вам необходимо включить приложение «Темы» в Nextcloud для доступа к глобальным настройкам.\n\n### Персональный\n\nПерсональный параметр позволяет каждому пользователю устанавливать свои собственные предпочтения независимо от того, как вы устанавливаете глобальный параметр. Если пользователь еще не установил параметр, он будет следовать глобальному параметру. Здесь вы можете найти персональный параметр:\n\n``\nПерсональные настройки > Специальные возможности > Breeze Dark\n`` ''\n\nОбратите внимание, что для доступа к личным настройкам в Nextcloud необходимо включить приложение «Специальные возможности».\n\n### Индивидуальный стиль\n\nВ разделе «Темы» в настройках администратора вы можете добавить в тему свой собственный стиль. Можно использовать только стандартный CSS. Этот пользовательский стиль будет применяться всякий раз, когда тема включена, и влияет только на тему Breeze Dark.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Тёмная тема, основанная на Breeze Dark от проекта KDE. Обновите страницу, чтобы изменения вступили в силу.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Этот параметр будет включать тему по умолчанию для всех пользователей, не прошедших проверку подлинности, и пользователей, которые не установили предпочтения.",
    "Enable Breeze Dark theme by default" : "Включить тему Breeze Dark по умолчанию",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Этот параметр позволит вам выбрать, должна ли страница входа быть тематической, если тема включена по умолчанию.",
    "Theme the login page" : "Тема на странице входа",
    "Custom Styling" : "Индивидуальный стиль",
    "Insert custom styling here …" : "Вставьте здесь собственный стиль…",
    "Save" : "Сохранить",
    "A Breeze Dark theme for Nextcloud." : "Тема Breeze Dark для Nextcloud.",
    "Breeze Dark theme" : "Тема Breeze Dark",
    "Enable Breeze Dark theme" : "Включить тему Breeze Dark"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
