OC.L10N.register(
    "breezedark",
    {
    "Saved" : "Sarvadu",
    "Error" : "Errore",
    "Breeze Dark" : "Breeze Dark",
    "Breeze Dark theme for Nextcloud, based on the theme by KDE" : "Tema Breeze Dark pro Nextcloud, basadu subra de su tema de KDE",
    "# Breeze Dark\nThis is a breeze dark theme for Nextcloud, based on the Breeze Dark theme made by the KDE Project.\n\n## Usage\n\nAfter you install the theme, you need to enable it. There a two options for this, a global and a personal one.\n\n### Global\n\nThe global option enables the theme by default for all users and unauthenticated visits. Without this option items like the login and sharing pages won't be styled. There is also an option to exclude the login page from being themed. You can find the global options here:\n\n```\nAdmin settings > Theming > Breeze Dark\n```\n\nPlease note that you need the Theming app enabled in Nextcloud to access the global settings.\n\n### Personal\n\nThe personal option allows each user to set their own preference independent of how you set the global option. If the user hasn't set an option yet, they will follow the global option. You can find the personal option here:\n\n```\nPersonal settings > Accessibility > Breeze Dark\n```\n\nPlease note that you need the Accessibility app enabled in Nextcloud to access the personal setting.\n\n### Custom styling\n\nUnder the Theming section in the admin settings you can add your own custom styling to the theme. Only standard CSS can be used. This custom styling will be applied whenever the theme is enabled and only affects the Breeze Dark theme." : "# Breeze Dark\nCustu est unu tema Breeze iscuru pro Nextcloud, basadu subra de su tema Breeze Dark fatu dae su progetu KDE.\n\n## Impreu\n\nA pustis de installare su tema, ddu depes ativare. B'at duos sèberos pro ddu fàghere, unu globale e un'àteru personale.\n\n### Globale\n\nSu sèberu globale ativat su tema comente predefinidu pro totu is utentes e is bìsitas sena identificatzione. Sena custu sèberu, elementos che a is pàginas de identificatzione e de cumpartzidura no ant a impreare su tema. B'at puru unu sèberu pro esclùdere sa pàgina de intrada de s'impreu de su tema. Podes agatare is sèberos globales inoghe:\n\n```\nCunfiguratziones de amministratzione > Temas > Breeze Dark\n```\n\nDae cara chi ti depes ativare s'aplicatzione Temas in Nextcloud pro atzèdere a is cunfiguratziones globales.\n\n### Personale\n\nSu sèberu personale permitit a ogni persone de cunfigurare sa preferèntzia sua, sena de cunsiderare comente apas cunfiguradu su sèberu globale. Si s'utente no at impostadu perunu sèberu ancora, at a èssere aplicadu su sèberu globale. Podes agatare su sèberu personale inoghe:\n\n```\nCunfiguratziones personales > Atzessibilidade > Breeze Dark\n```\n\nDae cara chi depes ativare s'aplicatzione Atzessibilidade in Nextcloud pro atzèdere a sa cunfiguratzione personale.\n\n### Istile personalizadu\n\nA intro de sa setzione Temas de is cunfiguratziones de amministratzione, podes agiùnghere s'istile tuo a su tema. Podes impreare isceti CSS istandard. Custu istile personalizadu at a èssere aplicadu cando su tema siat ativu e interessat isceti su tema Dark Breeze.",
    "A Dark theme based on Breeze Dark by the KDE project. Please refresh the page for changes to take effect." : "Tema iscuru basadu subra de Breeze Dark dae su progetu KDE. Atualiza sa pàgina pro chi is modìficas tèngiant efetu.",
    "This setting will enable the theme by default, for any unauthenticated users and users who haven't set a preference." : "Custa cunfiguratzione at a ativare su tema in manera predefinida pro cale si siat utente sena identificatzione e pro utentes chi no apant cunfiguradu una preferèntzia.",
    "Enable Breeze Dark theme by default" : "Ativa su tema Breeze Dark comente predefinidu",
    "This setting will allow you to choose if the login page should be themed when the theme is enabled by default." : "Custa cunfiguratzione t'at a permìtere de seberare si sa pàgina de intrada depet èssere ammustrada cun su tema predefinidu ativu.",
    "Theme the login page" : "Imprea su tema pro sa pàgina de intrada",
    "Custom Styling" : "Istile personalizadu",
    "Insert custom styling here …" : "Inserta s'istile personalizadu inoghe...",
    "Save" : "Sarva",
    "A Breeze Dark theme for Nextcloud." : "Tema Breeze Dark pro Nextcloud.",
    "Breeze Dark theme" : "Tema Breeze Dark",
    "Enable Breeze Dark theme" : "Ativa su tema Breeze Dark"
},
"nplurals=2; plural=(n != 1);");
